"""
Export tidy_score + language recommendations for selected desk images.
Writes language_score_results.md in the project root.

Usage:
    python export_language_scores.py
"""

from __future__ import annotations

from pathlib import Path

from ultralytics import YOLO

import run_pipeline as rp
from desk_language_recommend import generate_language_recommendations

PROJECT = Path(__file__).resolve().parent
IMAGES = [
    "desk_125.jpg",
    "desk_074.jpg",
    "desk_066.jpg",
    "desk_022.jpg",
]


def main() -> None:
    yolo = YOLO(str(rp.YOLO_MODEL))
    lines: list[str] = []
    lines.append("# Language scoring & tidy score results\n")
    lines.append("Generated by `export_language_scores.py` (YOLO + `tidy_score` + rule-based language module).\n")

    for fname in IMAGES:
        path = PROJECT / "jpg_images" / fname
        if not path.exists():
            lines.append(f"\n## {fname}\n\n**ERROR:** file not found: `{path}`\n")
            continue

        detections, orig_shape, _ = rp.run_yolo(
            yolo,
            str(path),
            conf=0.4,
            iou=0.5,
            imgsz=640,
            device="cpu",
            estimate_angles=True,
        )
        h, w = orig_shape
        score_result = rp.tidy_score(
            detections,
            image_size=(w, h),
            desk_orientation_deg=0.0,
            alignment_misalignment_threshold_deg=15.0,
            overlap_mode="mask",
        )
        rec = generate_language_recommendations(detections, score_result)

        lines.append(f"\n## {path.stem}\n")
        lines.append(f"- **Image:** `{path.name}`\n")
        lines.append(f"- **Tidy score:** {rec['tidy_score']}  \n")
        lines.append(f"- **Tidy level:** {rec['tidy_level']}  \n")
        lines.append(f"- **Decision:** {rec['decision']}  \n")
        lines.append(f"- **Total penalty:** {score_result.get('total_penalty', '—')}  \n")

        lines.append("\n### Reasons\n")
        for r in rec["reasons"]:
            lines.append(f"- {r}\n")

        lines.append("\n### Suggestions\n")
        for s in rec["suggestions"]:
            lines.append(f"- {s}\n")

        lines.append("\n### Grouped actions\n")
        for row in rec.get("grouped_actions", []):
            lines.append(
                f"- **{row['action']}** → {row['zone']}: {row['items']}\n"
            )

        lines.append("\n### Scoring explanation (reasons from tidy_score)\n")
        for r in score_result.get("explanation", {}).get("reasons", []):
            lines.append(f"- {r}\n")

        pen = score_result.get("penalties", {})
        if pen:
            lines.append("\n### Penalties (detail)\n")
            for k, v in sorted(pen.items()):
                lines.append(f"- `{k}`: {v}\n")

    out = PROJECT / "language_score_results.md"
    out.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote: {out}")


if __name__ == "__main__":
    main()
